<?php

Namespace Database\Seeders;

use App\Models\Modele;
use Illuminate\Database\Seeder;

class ModeleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Modele::insert([
            ['name' => '595','slug' => ' ','make_id' => '1'],
            ['name' => '695','slug' => ' ','make_id' => '1'],
            ['name' => '124 SPIDER','slug' => ' ','make_id' => '1'],
            ['name' => '4C','slug' => ' ','make_id' => '2'],
            ['name' => 'GIULIA','slug' => ' ','make_id' => '2'],
            ['name' => 'GIULIETTA','slug' => ' ','make_id' => '2'],
            ['name' => 'STELVIO','slug' => ' ','make_id' => '2'],
            ['name' => 'DB11','slug' => ' ','make_id' => '3'],
            ['name' => 'RAPIDE','slug' => ' ','make_id' => '3'],
            ['name' => 'VANQUISH S','slug' => ' ','make_id' => '3'],
            ['name' => 'VANTAGE','slug' => ' ','make_id' => '3'],
            ['name' => 'A1','slug' => ' ','make_id' => '4'],
            ['name' => 'A1 CITYCARVER','slug' => ' ','make_id' => '4'],
            ['name' => 'A3','slug' => ' ','make_id' => '4'],
            ['name' => 'A3 SPORTBACK','slug' => ' ','make_id' => '4'],
            ['name' => 'A4','slug' => ' ','make_id' => '4'],
            ['name' => 'A4 ALLROAD QUATTRO','slug' => ' ','make_id' => '4'],
            ['name' => 'A4 AVANT','slug' => ' ','make_id' => '4'],
            ['name' => 'A5','slug' => ' ','make_id' => '4'],
            ['name' => 'A5 CABRIOLET','slug' => ' ','make_id' => '4'],
            ['name' => 'A5 SPORTBACK','slug' => ' ','make_id' => '4'],
            ['name' => 'A6','slug' => ' ','make_id' => '4'],
            ['name' => 'A6 ALLROAD','slug' => ' ','make_id' => '4'],
            ['name' => 'A7 SPORTBACK','slug' => ' ','make_id' => '4'],
            ['name' => 'A8','slug' => ' ','make_id' => '4'],
            ['name' => 'E-TRON','slug' => ' ','make_id' => '4'],
            ['name' => 'E-TRON SPORTBACK','slug' => ' ','make_id' => '4'],
            ['name' => 'Q2','slug' => ' ','make_id' => '4'],
            ['name' => 'Q3','slug' => ' ','make_id' => '4'],
            ['name' => 'Q3 SPORTBACK','slug' => ' ','make_id' => '4'],
            ['name' => 'Q5','slug' => ' ','make_id' => '4'],
            ['name' => 'Q7','slug' => ' ','make_id' => '4'],
            ['name' => 'Q8','slug' => ' ','make_id' => '4'],
            ['name' => 'R8','slug' => ' ','make_id' => '4'],
            ['name' => 'RS Q3','slug' => ' ','make_id' => '4'],
            ['name' => 'RS Q3 SPORTBACK','slug' => ' ','make_id' => '4'],
            ['name' => 'RS3','slug' => ' ','make_id' => '4'],
            ['name' => 'RS4','slug' => ' ','make_id' => '4'],
            ['name' => 'RS5','slug' => ' ','make_id' => '4'],
            ['name' => 'RS6 AVANT','slug' => ' ','make_id' => '4'],
            ['name' => 'S3','slug' => ' ','make_id' => '4'],
            ['name' => 'S3 CABRIOLET','slug' => ' ','make_id' => '4'],
            ['name' => 'S4','slug' => ' ','make_id' => '4'],
            ['name' => 'S4 AVANT','slug' => ' ','make_id' => '4'],
            ['name' => 'S5','slug' => ' ','make_id' => '4'],
            ['name' => 'S5 CABRIOLET','slug' => ' ','make_id' => '4'],
            ['name' => 'S6','slug' => ' ','make_id' => '4'],
            ['name' => 'S6 AVANT','slug' => ' ','make_id' => '4'],
            ['name' => 'S7 SPORTBACK','slug' => ' ','make_id' => '4'],
            ['name' => 'S8','slug' => ' ','make_id' => '4'],
            ['name' => 'SQ2','slug' => ' ','make_id' => '4'],
            ['name' => 'SQ5','slug' => ' ','make_id' => '4'],
            ['name' => 'SQ7','slug' => ' ','make_id' => '4'],
            ['name' => 'SQ8','slug' => ' ','make_id' => '4'],
            ['name' => 'TT','slug' => ' ','make_id' => '4'],
            ['name' => 'TTS','slug' => ' ','make_id' => '4'],
            ['name' => 'BENTAYGA','slug' => ' ','make_id' => '5'],
            ['name' => 'CONTINENTAL','slug' => ' ','make_id' => '5'],
            ['name' => 'FLYING SPUR','slug' => ' ','make_id' => '5'],
            ['name' => 'MULSANNE','slug' => ' ','make_id' => '5'],
            ['name' => 'I3','slug' => ' ','make_id' => '6'],
            ['name' => 'I8','slug' => ' ','make_id' => '6'],
            ['name' => 'M2','slug' => ' ','make_id' => '6'],
            ['name' => 'M4','slug' => ' ','make_id' => '6'],
            ['name' => 'M5','slug' => ' ','make_id' => '6'],
            ['name' => 'M8 COMPETITION CABRIOLET','slug' => ' ','make_id' => '6'],
            ['name' => 'M8 COMPETITION COUPE','slug' => ' ','make_id' => '6'],
            ['name' => 'M8 COMPETITION GRAN COUPE','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 1','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 2','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 2 GRAN COUPE','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 3','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 3 TOURING','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 4','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 5','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 6','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 7','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 8 CABRIOLET','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 8 COUPE','slug' => ' ','make_id' => '6'],
            ['name' => 'SERIE 8 GRAN COUPE','slug' => ' ','make_id' => '6'],
            ['name' => 'X1','slug' => ' ','make_id' => '6'],
            ['name' => 'X2','slug' => ' ','make_id' => '6'],
            ['name' => 'X3','slug' => ' ','make_id' => '6'],
            ['name' => 'X4','slug' => ' ','make_id' => '6'],
            ['name' => 'X5','slug' => ' ','make_id' => '6'],
            ['name' => 'X5 M COMPETITION','slug' => ' ','make_id' => '6'],
            ['name' => 'X6','slug' => ' ','make_id' => '6'],
            ['name' => 'X6 M COMPETITION','slug' => ' ','make_id' => '6'],
            ['name' => 'X7','slug' => ' ','make_id' => '6'],
            ['name' => 'Z4','slug' => ' ','make_id' => '6'],
            ['name' => 'BERLINGO','slug' => ' ','make_id' => '7'],
            ['name' => 'C1','slug' => ' ','make_id' => '7'],
            ['name' => 'C3','slug' => ' ','make_id' => '7'],
            ['name' => 'C4','slug' => ' ','make_id' => '7'],
            ['name' => 'C5','slug' => ' ','make_id' => '7'],
            ['name' => 'C-ZERO','slug' => ' ','make_id' => '7'],
            ['name' => 'E-BERLINGO MULTISPACE','slug' => ' ','make_id' => '7'],
            ['name' => 'E-MEHARI','slug' => ' ','make_id' => '7'],
            ['name' => 'GRAND C4','slug' => ' ','make_id' => '7'],
            ['name' => 'JUMPER COMBI','slug' => ' ','make_id' => '7'],
            ['name' => 'JUMPY COMBI','slug' => ' ','make_id' => '7'],
            ['name' => 'SPACETOURER','slug' => ' ','make_id' => '7'],
            ['name' => 'DOKKER','slug' => ' ','make_id' => '8'],
            ['name' => 'DUSTER','slug' => ' ','make_id' => '8'],
            ['name' => 'LODGY','slug' => ' ','make_id' => '8'],
            ['name' => 'LOGAN','slug' => ' ','make_id' => '8'],
            ['name' => 'SANDERO','slug' => ' ','make_id' => '8'],
            ['name' => 'DS3','slug' => ' ','make_id' => '9'],
            ['name' => 'DS3 CABRIOLET','slug' => ' ','make_id' => '9'],
            ['name' => 'DS3 CROSSBACK','slug' => ' ','make_id' => '9'],
            ['name' => 'DS3 EXECUTIVE','slug' => ' ','make_id' => '9'],
            ['name' => 'DS4','slug' => ' ','make_id' => '9'],
            ['name' => 'DS4 EXECUTIVE','slug' => ' ','make_id' => '9'],
            ['name' => 'DS5','slug' => ' ','make_id' => '9'],
            ['name' => 'DS5 EXECUTIVE','slug' => ' ','make_id' => '9'],
            ['name' => 'DS7 CROSSBACK','slug' => ' ','make_id' => '9'],
            ['name' => 'DS7 CROSSBACK EXECUTIVE','slug' => ' ','make_id' => '9'],
            ['name' => '488 CHALLENGE','slug' => ' ','make_id' => '10'],
            ['name' => '488 GTB','slug' => ' ','make_id' => '10'],
            ['name' => '488 PISTA','slug' => ' ','make_id' => '10'],
            ['name' => '488 PISTA SPIDER','slug' => ' ','make_id' => '10'],
            ['name' => '488 SPIDER','slug' => ' ','make_id' => '10'],
            ['name' => '812 SUPERFAST','slug' => ' ','make_id' => '10'],
            ['name' => 'F8 TRIBUTO','slug' => ' ','make_id' => '10'],
            ['name' => 'GTC4 LUSSO','slug' => ' ','make_id' => '10'],
            ['name' => 'MONZA SP1','slug' => ' ','make_id' => '10'],
            ['name' => 'MONZA SP2','slug' => ' ','make_id' => '10'],
            ['name' => 'PORTOFINO','slug' => ' ','make_id' => '10'],
            ['name' => 'SF90 STRADALE','slug' => ' ','make_id' => '10'],
            ['name' => '500','slug' => ' ','make_id' => '11'],
            ['name' => '500C','slug' => ' ','make_id' => '11'],
            ['name' => '500L','slug' => ' ','make_id' => '11'],
            ['name' => '500X','slug' => ' ','make_id' => '11'],
            ['name' => 'DOBLO','slug' => ' ','make_id' => '11'],
            ['name' => 'DUCATO COMBI','slug' => ' ','make_id' => '11'],
            ['name' => 'FIORINO','slug' => ' ','make_id' => '11'],
            ['name' => 'PANDA','slug' => ' ','make_id' => '11'],
            ['name' => 'QUBO','slug' => ' ','make_id' => '11'],
            ['name' => 'TALENTO PANORAMA','slug' => ' ','make_id' => '11'],
            ['name' => 'TIPO','slug' => ' ','make_id' => '11'],
            ['name' => 'TIPO 5 PORTES','slug' => ' ','make_id' => '11'],
            ['name' => 'TIPO STATION WAGON','slug' => ' ','make_id' => '11'],
            ['name' => 'C-MAX','slug' => ' ','make_id' => '12'],
            ['name' => 'ECOSPORT','slug' => ' ','make_id' => '12'],
            ['name' => 'EDGE','slug' => ' ','make_id' => '12'],
            ['name' => 'EXPLORER','slug' => ' ','make_id' => '12'],
            ['name' => 'FIESTA','slug' => ' ','make_id' => '12'],
            ['name' => 'FOCUS','slug' => ' ','make_id' => '12'],
            ['name' => 'FOCUS SW','slug' => ' ','make_id' => '12'],
            ['name' => 'GALAXY','slug' => ' ','make_id' => '12'],
            ['name' => 'GRAND C-MAX','slug' => ' ','make_id' => '12'],
            ['name' => 'KA+','slug' => ' ','make_id' => '12'],
            ['name' => 'KUGA HYBRIDE RECHARGEABLE','slug' => ' ','make_id' => '12'],
            ['name' => 'MONDEO','slug' => ' ','make_id' => '12'],
            ['name' => 'MONDEO SW','slug' => ' ','make_id' => '12'],
            ['name' => 'MUSTANG','slug' => ' ','make_id' => '12'],
            ['name' => 'PUMA','slug' => ' ','make_id' => '12'],
            ['name' => 'S-MAX','slug' => ' ','make_id' => '12'],
            ['name' => 'TOURNEO','slug' => ' ','make_id' => '12'],
            ['name' => 'TRANSIT','slug' => ' ','make_id' => '12'],
            ['name' => 'CIVIC','slug' => ' ','make_id' => '13'],
            ['name' => 'CIVIC 4 PORTES','slug' => ' ','make_id' => '13'],
            ['name' => 'CIVIC TYPE R','slug' => ' ','make_id' => '13'],
            ['name' => 'CR-V','slug' => ' ','make_id' => '13'],
            ['name' => 'CR-V HYBRID','slug' => ' ','make_id' => '13'],
            ['name' => 'HONDA E','slug' => ' ','make_id' => '13'],
            ['name' => 'HR-V','slug' => ' ','make_id' => '13'],
            ['name' => 'JAZZ','slug' => ' ','make_id' => '13'],
            ['name' => 'NSX','slug' => ' ','make_id' => '13'],
            ['name' => 'I10','slug' => ' ','make_id' => '14'],
            ['name' => 'I20','slug' => ' ','make_id' => '14'],
            ['name' => 'I30','slug' => ' ','make_id' => '14'],
            ['name' => 'I40','slug' => ' ','make_id' => '14'],
            ['name' => 'IONIQ','slug' => ' ','make_id' => '14'],
            ['name' => 'KONA','slug' => ' ','make_id' => '14'],
            ['name' => 'NEXO','slug' => ' ','make_id' => '14'],
            ['name' => 'SANTA FE','slug' => ' ','make_id' => '14'],
            ['name' => 'TUCSON','slug' => ' ','make_id' => '14'],
            ['name' => 'Q30','slug' => ' ','make_id' => '15'],
            ['name' => 'Q50','slug' => ' ','make_id' => '15'],
            ['name' => 'Q60','slug' => ' ','make_id' => '15'],
            ['name' => 'Q70','slug' => ' ','make_id' => '15'],
            ['name' => 'QX30','slug' => ' ','make_id' => '15'],
            ['name' => 'QX70','slug' => ' ','make_id' => '15'],
            ['name' => 'E-PACE','slug' => ' ','make_id' => '16'],
            ['name' => 'F-PACE','slug' => ' ','make_id' => '16'],
            ['name' => 'F-TYPE CABRIOLET','slug' => ' ','make_id' => '16'],
            ['name' => 'F-TYPE CABRIOLETSVR','slug' => ' ','make_id' => '16'],
            ['name' => 'F-TYPE COUPE','slug' => ' ','make_id' => '16'],
            ['name' => 'F-TYPE COUPE SVR','slug' => ' ','make_id' => '16'],
            ['name' => 'I-PACE','slug' => ' ','make_id' => '16'],
            ['name' => 'XE','slug' => ' ','make_id' => '16'],
            ['name' => 'XF','slug' => ' ','make_id' => '16'],
            ['name' => 'XF SPORTBRAKE','slug' => ' ','make_id' => '16'],
            ['name' => 'XJ','slug' => ' ','make_id' => '16'],
            ['name' => 'CHEROKEE','slug' => ' ','make_id' => '17'],
            ['name' => 'COMPASS','slug' => ' ','make_id' => '17'],
            ['name' => 'GRAND CHEROKEE','slug' => ' ','make_id' => '17'],
            ['name' => 'RENEGADE','slug' => ' ','make_id' => '17'],
            ['name' => 'WRANGLER','slug' => ' ','make_id' => '17'],
            ['name' => 'CEED','slug' => ' ','make_id' => '18'],
            ['name' => 'CEED SW','slug' => ' ','make_id' => '18'],
            ['name' => 'E-NIRO','slug' => ' ','make_id' => '18'],
            ['name' => 'E-SOUL','slug' => ' ','make_id' => '18'],
            ['name' => 'NIRO','slug' => ' ','make_id' => '18'],
            ['name' => 'OPTIMA SW','slug' => ' ','make_id' => '18'],
            ['name' => 'PICANTO','slug' => ' ','make_id' => '18'],
            ['name' => 'PROCEED','slug' => ' ','make_id' => '18'],
            ['name' => 'RIO','slug' => ' ','make_id' => '18'],
            ['name' => 'SORENTO','slug' => ' ','make_id' => '18'],
            ['name' => 'SPORTAGE','slug' => ' ','make_id' => '18'],
            ['name' => 'STINGER','slug' => ' ','make_id' => '18'],
            ['name' => 'STONIC','slug' => ' ','make_id' => '18'],
            ['name' => 'XCEED','slug' => ' ','make_id' => '18'],
            ['name' => '4X4','slug' => ' ','make_id' => '19'],
            ['name' => 'GRANTA','slug' => ' ','make_id' => '19'],
            ['name' => 'PRIORA','slug' => ' ','make_id' => '19'],
            ['name' => 'PRIORA BREAK','slug' => ' ','make_id' => '19'],
            ['name' => 'AVENTADOR S','slug' => ' ','make_id' => '20'],
            ['name' => 'AVENTADOR S ROADSTER','slug' => ' ','make_id' => '20'],
            ['name' => 'AVENTADOR SVJ','slug' => ' ','make_id' => '20'],
            ['name' => 'AVENTADOR SVJ ROADSTER','slug' => ' ','make_id' => '20'],
            ['name' => 'HURACAN','slug' => ' ','make_id' => '20'],
            ['name' => 'HURACAN EVO','slug' => ' ','make_id' => '20'],
            ['name' => 'HURACAN EVO SPYDER','slug' => ' ','make_id' => '20'],
            ['name' => 'HURACAN SPYDER','slug' => ' ','make_id' => '20'],
            ['name' => 'URUS','slug' => ' ','make_id' => '20'],
            ['name' => 'DEFENDER','slug' => ' ','make_id' => '21'],
            ['name' => 'DISCOVERY','slug' => ' ','make_id' => '21'],
            ['name' => 'DISCOVERY SPORT','slug' => ' ','make_id' => '21'],
            ['name' => 'RANGE ROVER','slug' => ' ','make_id' => '21'],
            ['name' => 'RANGE ROVER EVOQUE','slug' => ' ','make_id' => '21'],
            ['name' => 'RANGE ROVER EVOQUE CABRIOLET','slug' => ' ','make_id' => '21'],
            ['name' => 'RANGE ROVER SPORT','slug' => ' ','make_id' => '21'],
            ['name' => 'RANGE ROVER VELAR','slug' => ' ','make_id' => '21'],
            ['name' => 'CT','slug' => ' ','make_id' => '22'],
            ['name' => 'ES','slug' => ' ','make_id' => '22'],
            ['name' => 'IS','slug' => ' ','make_id' => '22'],
            ['name' => 'LC','slug' => ' ','make_id' => '22'],
            ['name' => 'LS','slug' => ' ','make_id' => '22'],
            ['name' => 'NX','slug' => ' ','make_id' => '22'],
            ['name' => 'RC','slug' => ' ','make_id' => '22'],
            ['name' => 'RX','slug' => ' ','make_id' => '22'],
            ['name' => 'UX','slug' => ' ','make_id' => '22'],
            ['name' => 'ELISE','slug' => ' ','make_id' => '23'],
            ['name' => 'EVORA','slug' => ' ','make_id' => '23'],
            ['name' => 'EXIGE','slug' => ' ','make_id' => '23'],
            ['name' => 'EXIGE ROADSTER','slug' => ' ','make_id' => '23'],
            ['name' => 'GHIBLI','slug' => ' ','make_id' => '24'],
            ['name' => 'GRANCABRIO','slug' => ' ','make_id' => '24'],
            ['name' => 'GRANTURISMO','slug' => ' ','make_id' => '24'],
            ['name' => 'LEVANTE','slug' => ' ','make_id' => '24'],
            ['name' => 'QUATTROPORTE','slug' => ' ','make_id' => '24'],
            ['name' => 'CX-30','slug' => ' ','make_id' => '25'],
            ['name' => 'CX-5','slug' => ' ','make_id' => '25'],
            ['name' => 'MAZDA 2','slug' => ' ','make_id' => '25'],
            ['name' => 'MAZDA3','slug' => ' ','make_id' => '25'],
            ['name' => 'MAZDA3 BERLINE','slug' => ' ','make_id' => '25'],
            ['name' => 'MAZDA6 NORME EVAP','slug' => ' ','make_id' => '25'],
            ['name' => 'MAZDA6 WAGON NORME EVAP','slug' => ' ','make_id' => '25'],
            ['name' => 'MX-30','slug' => ' ','make_id' => '25'],
            ['name' => 'MX-5 RF','slug' => ' ','make_id' => '25'],
            ['name' => 'MX-5 ST','slug' => ' ','make_id' => '25'],
            ['name' => 'MCLAREN 570S SPIDER','slug' => ' ','make_id' => '26'],
            ['name' => 'MCLAREN 720S COUPE','slug' => ' ','make_id' => '26'],
            ['name' => 'MCLAREN COUPE 540C','slug' => ' ','make_id' => '26'],
            ['name' => 'MCLAREN COUPE 570GT','slug' => ' ','make_id' => '26'],
            ['name' => 'MCLAREN COUPE 570S','slug' => ' ','make_id' => '26'],
            ['name' => 'AMG GT COUPE','slug' => ' ','make_id' => '27'],
            ['name' => 'AMG GT COUPE 4P','slug' => ' ','make_id' => '27'],
            ['name' => 'AMG GT ROADSTER','slug' => ' ','make_id' => '27'],
            ['name' => 'CITAN TOURER','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE A','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE B','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE C','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE C BREAK','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE C CABRIOLET','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE C COUPE','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE CLA COUPà‰','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE CLA SHOOTING BRAKE','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE CLS','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE E','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE E BREAK','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE E CABRIOLET','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE E COUPE','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE G','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE GLA','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE GLC','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE GLC COUPE','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE GLE','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE GLE COUPE','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE S','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE S CABRIOLET','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE S COUPE','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE SL','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE SLC','slug' => ' ','make_id' => '27'],
            ['name' => 'CLASSE V','slug' => ' ','make_id' => '27'],
            ['name' => 'EQC','slug' => ' ','make_id' => '27'],
            ['name' => 'GLB','slug' => ' ','make_id' => '27'],
            ['name' => 'GLS','slug' => ' ','make_id' => '27'],
            ['name' => 'MARCO POLO','slug' => ' ','make_id' => '27'],
            ['name' => 'MARCO POLO ACTIVITY','slug' => ' ','make_id' => '27'],
            ['name' => 'SPRINTER TOURER','slug' => ' ','make_id' => '27'],
            ['name' => 'VITO TOURER','slug' => ' ','make_id' => '27'],
            ['name' => '3 PORTES','slug' => ' ','make_id' => '28'],
            ['name' => '5 PORTES','slug' => ' ','make_id' => '28'],
            ['name' => 'CABRIO','slug' => ' ','make_id' => '28'],
            ['name' => 'CLUBMAN','slug' => ' ','make_id' => '28'],
            ['name' => 'COUNTRYMAN','slug' => ' ','make_id' => '28'],
            ['name' => 'MINI CLUBMAN','slug' => ' ','make_id' => '28'],
            ['name' => 'MINI ELECTRIC','slug' => ' ','make_id' => '28'],
            ['name' => 'MINI JOHN COOPER WORKS GP','slug' => ' ','make_id' => '28'],
            ['name' => 'ASX','slug' => ' ','make_id' => '29'],
            ['name' => 'ECLIPSE CROSS','slug' => ' ','make_id' => '29'],
            ['name' => 'OUTLANDER','slug' => ' ','make_id' => '29'],
            ['name' => 'SPACE STAR','slug' => ' ','make_id' => '29'],
            ['name' => '370Z','slug' => ' ','make_id' => '30'],
            ['name' => '370Z COUPE','slug' => ' ','make_id' => '30'],
            ['name' => 'EVALIA','slug' => ' ','make_id' => '30'],
            ['name' => 'GT-R','slug' => ' ','make_id' => '30'],
            ['name' => 'JUKE','slug' => ' ','make_id' => '30'],
            ['name' => 'LEAF','slug' => ' ','make_id' => '30'],
            ['name' => 'MICRA','slug' => ' ','make_id' => '30'],
            ['name' => 'NV300 COMBI','slug' => ' ','make_id' => '30'],
            ['name' => 'PULSAR','slug' => ' ','make_id' => '30'],
            ['name' => 'QASHQAI','slug' => ' ','make_id' => '30'],
            ['name' => 'X-TRAIL','slug' => ' ','make_id' => '30'],
            ['name' => 'ADAM','slug' => ' ','make_id' => '31'],
            ['name' => 'ASTRA','slug' => ' ','make_id' => '31'],
            ['name' => 'ASTRA GTC','slug' => ' ','make_id' => '31'],
            ['name' => 'ASTRA SPORTS TOURER','slug' => ' ','make_id' => '31'],
            ['name' => 'COMBO LIFE','slug' => ' ','make_id' => '31'],
            ['name' => 'CORSA','slug' => ' ','make_id' => '31'],
            ['name' => 'CROSSLAND X','slug' => ' ','make_id' => '31'],
            ['name' => 'GRANDLAND X','slug' => ' ','make_id' => '31'],
            ['name' => 'INSIGNIA GRAND SPORT','slug' => ' ','make_id' => '31'],
            ['name' => 'INSIGNIA SPORTS TOURER','slug' => ' ','make_id' => '31'],
            ['name' => 'KARL','slug' => ' ','make_id' => '31'],
            ['name' => 'MOKKA X','slug' => ' ','make_id' => '31'],
            ['name' => 'MOVANO COMBI','slug' => ' ','make_id' => '31'],
            ['name' => 'VIVARO COMBI','slug' => ' ','make_id' => '31'],
            ['name' => 'ZAFIRA LIFE','slug' => ' ','make_id' => '31'],
            ['name' => '108','slug' => ' ','make_id' => '32'],
            ['name' => '208','slug' => ' ','make_id' => '32'],
            ['name' => '308','slug' => ' ','make_id' => '32'],
            ['name' => '508','slug' => ' ','make_id' => '32'],
            ['name' => '2008','slug' => ' ','make_id' => '32'],
            ['name' => '3008','slug' => ' ','make_id' => '32'],
            ['name' => '5008','slug' => ' ','make_id' => '32'],
            ['name' => '308 SW','slug' => ' ','make_id' => '32'],
            ['name' => '508 SW','slug' => ' ','make_id' => '32'],
            ['name' => 'BOXER COMBI','slug' => ' ','make_id' => '32'],
            ['name' => 'E-PARTNER TEPEE','slug' => ' ','make_id' => '32'],
            ['name' => 'EXPERT COMBI','slug' => ' ','make_id' => '32'],
            ['name' => 'ION','slug' => ' ','make_id' => '32'],
            ['name' => 'RIFTER','slug' => ' ','make_id' => '32'],
            ['name' => 'TRAVELLER','slug' => ' ','make_id' => '32'],
            ['name' => '718','slug' => ' ','make_id' => '33'],
            ['name' => '718 CAYMAN GT4','slug' => ' ','make_id' => '33'],
            ['name' => '718 SPYDER','slug' => ' ','make_id' => '33'],
            ['name' => '911 CARRERA CABRIOLET','slug' => ' ','make_id' => '33'],
            ['name' => '911 CARRERA COUPE','slug' => ' ','make_id' => '33'],
            ['name' => '911 GT3 RS','slug' => ' ','make_id' => '33'],
            ['name' => '911 SPEEDSTER','slug' => ' ','make_id' => '33'],
            ['name' => 'CAYENNE','slug' => ' ','make_id' => '33'],
            ['name' => 'CAYENNE COUPE','slug' => ' ','make_id' => '33'],
            ['name' => 'CAYMAN','slug' => ' ','make_id' => '33'],
            ['name' => 'MACAN','slug' => ' ','make_id' => '33'],
            ['name' => 'PANAMERA','slug' => ' ','make_id' => '33'],
            ['name' => 'TAYCAN','slug' => ' ','make_id' => '33'],
            ['name' => 'CAPTUR','slug' => ' ','make_id' => '34'],
            ['name' => 'CLIO','slug' => ' ','make_id' => '34'],
            ['name' => 'ESPACE V','slug' => ' ','make_id' => '34'],
            ['name' => 'GRAND SCENIC','slug' => ' ','make_id' => '34'],
            ['name' => 'KADJAR','slug' => ' ','make_id' => '34'],
            ['name' => 'KANGOO','slug' => ' ','make_id' => '34'],
            ['name' => 'KOLEOS','slug' => ' ','make_id' => '34'],
            ['name' => 'MASTER COMBI III','slug' => ' ','make_id' => '34'],
            ['name' => 'MEGANE','slug' => ' ','make_id' => '34'],
            ['name' => 'MEGANE ESTATE','slug' => ' ','make_id' => '34'],
            ['name' => 'SCENIC','slug' => ' ','make_id' => '34'],
            ['name' => 'TALISMAN','slug' => ' ','make_id' => '34'],
            ['name' => 'TALISMAN ESTATE','slug' => ' ','make_id' => '34'],
            ['name' => 'TRAFIC COMBI','slug' => ' ','make_id' => '34'],
            ['name' => 'TRAFIC NAVETTE','slug' => ' ','make_id' => '34'],
            ['name' => 'TWINGO','slug' => ' ','make_id' => '34'],
            ['name' => 'TWIZY','slug' => ' ','make_id' => '34'],
            ['name' => 'ZOE','slug' => ' ','make_id' => '34'],
            ['name' => 'GHOST','slug' => ' ','make_id' => '35'],
            ['name' => 'PHANTOM','slug' => ' ','make_id' => '35'],
            ['name' => 'PHANTOM CONVERTIBLE','slug' => ' ','make_id' => '35'],
            ['name' => 'PHANTOM COUPE','slug' => ' ','make_id' => '35'],
            ['name' => 'ALHAMBRA','slug' => ' ','make_id' => '36'],
            ['name' => 'ARONA','slug' => ' ','make_id' => '36'],
            ['name' => 'ATECA','slug' => ' ','make_id' => '36'],
            ['name' => 'IBIZA','slug' => ' ','make_id' => '36'],
            ['name' => 'LEON','slug' => ' ','make_id' => '36'],
            ['name' => 'LEON SC','slug' => ' ','make_id' => '36'],
            ['name' => 'LEON SPORTOURER ST','slug' => ' ','make_id' => '36'],
            ['name' => 'LEON SPORTSTOURER','slug' => ' ','make_id' => '36'],
            ['name' => 'LEON ST','slug' => ' ','make_id' => '36'],
            ['name' => 'MII','slug' => ' ','make_id' => '36'],
            ['name' => 'MII ELECTRIC','slug' => ' ','make_id' => '36'],
            ['name' => 'TARRACO','slug' => ' ','make_id' => '36'],
            ['name' => 'CITIGO E IV','slug' => ' ','make_id' => '37'],
            ['name' => 'FABIA','slug' => ' ','make_id' => '37'],
            ['name' => 'FABIA COMBI','slug' => ' ','make_id' => '37'],
            ['name' => 'KAMIQ','slug' => ' ','make_id' => '37'],
            ['name' => 'KAROQ','slug' => ' ','make_id' => '37'],
            ['name' => 'KODIAQ','slug' => ' ','make_id' => '37'],
            ['name' => 'OCTAVIA COMBI','slug' => ' ','make_id' => '37'],
            ['name' => 'SCALA','slug' => ' ','make_id' => '37'],
            ['name' => 'SUPERB','slug' => ' ','make_id' => '37'],
            ['name' => 'SUPERB COMBI','slug' => ' ','make_id' => '37'],
            ['name' => 'FORFOUR','slug' => ' ','make_id' => '38'],
            ['name' => 'FORTWO CABRIO','slug' => ' ','make_id' => '38'],
            ['name' => 'FORTWO COUPE','slug' => ' ','make_id' => '38'],
            ['name' => 'KORANDO','slug' => ' ','make_id' => '39'],
            ['name' => 'MUSSO','slug' => ' ','make_id' => '39'],
            ['name' => 'REXTON','slug' => ' ','make_id' => '39'],
            ['name' => 'TIVOLI','slug' => ' ','make_id' => '39'],
            ['name' => 'TIVOLI XLV','slug' => ' ','make_id' => '39'],
            ['name' => 'BRZ','slug' => ' ','make_id' => '40'],
            ['name' => 'FORESTER','slug' => ' ','make_id' => '40'],
            ['name' => 'IMPREZA','slug' => ' ','make_id' => '40'],
            ['name' => 'LEVORG','slug' => ' ','make_id' => '40'],
            ['name' => 'OUTBACK','slug' => ' ','make_id' => '40'],
            ['name' => 'XV','slug' => ' ','make_id' => '40'],
            ['name' => 'BALENO','slug' => ' ','make_id' => '41'],
            ['name' => 'CELERIO','slug' => ' ','make_id' => '41'],
            ['name' => 'IGNIS','slug' => ' ','make_id' => '41'],
            ['name' => 'JIMNY','slug' => ' ','make_id' => '41'],
            ['name' => 'S-CROSS','slug' => ' ','make_id' => '41'],
            ['name' => 'SWIFT','slug' => ' ','make_id' => '41'],
            ['name' => 'SWIFT SPORT','slug' => ' ','make_id' => '41'],
            ['name' => 'VITARA','slug' => ' ','make_id' => '41'],
            ['name' => 'MODEL 3','slug' => ' ','make_id' => '42'],
            ['name' => 'MODEL S','slug' => ' ','make_id' => '42'],
            ['name' => 'MODEL X','slug' => ' ','make_id' => '42'],
            ['name' => 'AVENSIS TOURING','slug' => ' ','make_id' => '43'],
            ['name' => 'AYGO','slug' => ' ','make_id' => '43'],
            ['name' => 'AYGO PRO','slug' => ' ','make_id' => '43'],
            ['name' => 'CAMRY','slug' => ' ','make_id' => '43'],
            ['name' => 'C-HR HYBRIDE','slug' => ' ','make_id' => '43'],
            ['name' => 'C-HR HYBRIDE PRO','slug' => ' ','make_id' => '43'],
            ['name' => 'COROLLA TOURING SPORTS PRO HYBRIDE','slug' => ' ','make_id' => '43'],
            ['name' => 'GT86','slug' => ' ','make_id' => '43'],
            ['name' => 'LAND CRUISER','slug' => ' ','make_id' => '43'],
            ['name' => 'MIRAI','slug' => ' ','make_id' => '43'],
            ['name' => 'PRIUS','slug' => ' ','make_id' => '43'],
            ['name' => 'PRIUS HYBRIDE','slug' => ' ','make_id' => '43'],
            ['name' => 'PRIUS HYBRIDE RECHARGEABLE','slug' => ' ','make_id' => '43'],
            ['name' => 'PRIUS PRO HYBRIDE','slug' => ' ','make_id' => '43'],
            ['name' => 'PRIUS PRO HYBRIDE RECHARGEABLE','slug' => ' ','make_id' => '43'],
            ['name' => 'PRIUS+','slug' => ' ','make_id' => '43'],
            ['name' => 'PROACE','slug' => ' ','make_id' => '43'],
            ['name' => 'PROACE CITY VERSO','slug' => ' ','make_id' => '43'],
            ['name' => 'PROACE COMBI','slug' => ' ','make_id' => '43'],
            ['name' => 'PROACE VERSO','slug' => ' ','make_id' => '43'],
            ['name' => 'RAV4 HYBRIDE','slug' => ' ','make_id' => '43'],
            ['name' => 'RAV4 HYBRIDE PRO','slug' => ' ','make_id' => '43'],
            ['name' => 'SUPRA','slug' => ' ','make_id' => '43'],
            ['name' => 'YARIS','slug' => ' ','make_id' => '43'],
            ['name' => 'YARIS HYBRIDE','slug' => ' ','make_id' => '43'],
            ['name' => 'YARIS HYBRIDE PRO','slug' => ' ','make_id' => '43'],
            ['name' => 'YARIS PRO','slug' => ' ','make_id' => '43'],
            ['name' => 'YARIS ULTIMATE','slug' => ' ','make_id' => '43'],
            ['name' => 'ARTEON','slug' => ' ','make_id' => '44'],
            ['name' => 'CADDY','slug' => ' ','make_id' => '44'],
            ['name' => 'CALIFORNIA','slug' => ' ','make_id' => '44'],
            ['name' => 'CALIFORNIA 6.1','slug' => ' ','make_id' => '44'],
            ['name' => 'CARAVELLE','slug' => ' ','make_id' => '44'],
            ['name' => 'COCCINELLE','slug' => ' ','make_id' => '44'],
            ['name' => 'E-GOLF','slug' => ' ','make_id' => '44'],
            ['name' => 'E-UP','slug' => ' ','make_id' => '44'],
            ['name' => 'GOLF','slug' => ' ','make_id' => '44'],
            ['name' => 'GOLF SPORTSVAN','slug' => ' ','make_id' => '44'],
            ['name' => 'GOLF SW','slug' => ' ','make_id' => '44'],
            ['name' => 'MULTIVAN','slug' => ' ','make_id' => '44'],
            ['name' => 'PASSAT','slug' => ' ','make_id' => '44'],
            ['name' => 'PASSAT SW','slug' => ' ','make_id' => '44'],
            ['name' => 'POLO','slug' => ' ','make_id' => '44'],
            ['name' => 'SCIROCCO','slug' => ' ','make_id' => '44'],
            ['name' => 'SHARAN','slug' => ' ','make_id' => '44'],
            ['name' => 'T-CROSS','slug' => ' ','make_id' => '44'],
            ['name' => 'TIGUAN','slug' => ' ','make_id' => '44'],
            ['name' => 'TOUAREG','slug' => ' ','make_id' => '44'],
            ['name' => 'TOURAN','slug' => ' ','make_id' => '44'],
            ['name' => 'T-ROC','slug' => ' ','make_id' => '44'],
            ['name' => 'UP','slug' => ' ','make_id' => '44'],
            ['name' => 'S60','slug' => ' ','make_id' => '45'],
            ['name' => 'S90','slug' => ' ','make_id' => '45'],
            ['name' => 'V60','slug' => ' ','make_id' => '45'],
            ['name' => 'V90','slug' => ' ','make_id' => '45'],
            ['name' => 'V90 CROSS COUNTRY','slug' => ' ','make_id' => '45'],
            ['name' => 'XC40','slug' => ' ','make_id' => '45'],
            ['name' => 'XC60','slug' => ' ','make_id' => '45'],
            ['name' => 'XC90','slug' => ' ','make_id' => '45'],
        ]);
    }
}
